# This file configures Dependabot for the repository.
# It specifies the package ecosystem, directory, schedule for updates,
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
      - "good first issue" # For minor updates suitable for new contributors
    assignees:
      - "nforshifu234"
    reviewers:
      - "nforshifu234"