version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root of the project
    schedule:
      interval: "weekly" # or "daily" / "monthly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "automated"
