name: Manage Stale PRs
# This workflow manages stale pull requests in the repository.
# It uses the `actions/stale` action to mark and close pull requests that have been inactive for a specified period.

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark and Close Stale PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: |
            This PR has been inactive for 30 days and is now marked as stale. If no activity occurs in 7 days, it will be closed to keep **nfsfu234-tour-guide** tidy. Please update or comment to keep it active. Thanks!
          close-pr-message: |
            This PR was closed due to 37 days of inactivity. Feel free to reopen or create a new PR to continue contributing to **nfsfu234-tour-guide**!
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: 'wontfix'
          exempt-pr-labels: 'good first issue,help wanted'